name: docker

on:
  push:
    branches: main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push the docker image to ghcr.io
        run: |
          echo $CR_PAT | docker login ghcr.io -u yasuyuky --password-stdin
          docker build -f Dockerfile.ja_JP . -t ghcr.io/yasuyuky/svg2pdf:latest
          docker push -a ghcr.io/yasuyuky/svg2pdf
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
